name: Dependabot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: read
  contents: write
  pull-requests: write
  statuses: read

jobs:
  auto-merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: HappyHackingSpace/actions/.github/workflows/dependabot-auto-merge.yaml@v1
